# Generated by Django 3.2.6 on 2021-08-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2056, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Commentaire',
            },
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Collaborateur',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
                ('tag', models.CharField(max_length=64, verbose_name='Type')),
                ('priority', models.CharField(max_length=64, verbose_name='Priorité')),
                ('status', models.CharField(max_length=64, verbose_name='Statut')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Problème',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Titre')),
                ('description', models.CharField(max_length=512, verbose_name='Description')),
                ('type', models.CharField(max_length=64, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Projet',
            },
        ),
    ]
